[phases.install]
cmds = ['yarn install --immutable']

[phases.build]
cmds = ['yarn build:backend']

[start]
cmd = 'cd apps/backend && chmod +x deploy.sh && ./deploy.sh && cd ../.. && yarn start:backend'