name: Chromatic

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build Storybook
        run: yarn nx run ui:build-storybook

      - name: Publish to Chromatic
        uses: chromaui/action@v11
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: libs/ui/storybook-static
          exitOnceUploaded: true
