name: PR Checks

on:
  pull_request:
    branches:
      - development

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run lint on affected projects
        run: yarn nx affected -t lint --base=origin/${{ github.base_ref }}
        env:
          NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY: 'sample_key_for_linting_purposes_only'

      - name: Run type-check on affected projects
        run: yarn nx affected -t type-check --base=origin/${{ github.base_ref }}
        env:
          DATABASE_URL: 'postgresql://user:password@localhost:5432/dummy_db'

      - name: Run tests on affected projects
        run: yarn nx affected -t test --base=origin/${{ github.base_ref }}
        env:
          DATABASE_URL: 'postgresql://user:password@localhost:5432/dummy_db'
          TEST_TYPE: 'unit'
